<style type="text/css">
<!--
input,textarea {
	font-family:monospace;
	font-size:10pt;
	}
body,p,dl,dt,dd,td,th,.submit {
	font-family:verdana,sans-serif;
	font-size:10pt;
	}
.submit {
	color:#000000;
	background-color:#ffffff;
	cursor:pointer;
	font-weight:bold;
	}
a:hover {
	color:#ff4444;
	background-color:#ffffff;
	}
b.hl1 {
	font-weight:bold;
	}
b.hl2 {
	font-weight:bold;
	font-style:italic;
	}
.sr {
	font-size:10pt;
	line-height:14pt;
	}
//-->
</style>
